import { Inter } from "next/font/google";
import "./globals.css";
// import { Analytics } from "@vercel/analytics/react";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Urbanist } from "next/font/google";

const gurb = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
  // variable: "--font-urbanist"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-mdwhite $ text-mblack`}>
        <section className="flex flex-col  h-screen justify-between w-full">
          <section className="bg-mdwhite ">
            <Header />
          </section>
          <section className={`${gurb.className} `}>
            <section className="max-w-screen-xl m-auto">{children}</section>
            {/* <Analytics /> */}
          </section>
          <section>
            <Footer />
          </section>
        </section>
      </body>
    </html>
  );
}
